### ISSUE TITLE
Supporting newPasswordRequired function

### ISSUE THREAD

**Issue by ddewaele** [dbroadhurst/aws-cognito-react#1]
Great job with the sample app !

When a user is created with a temp password, Cognito requires the user to reset the pwd after the initial login.

For that, the newPasswordRequired function is required (including a screen to set the new pwd).

**Comment by dbroadhurst** [comment]
Thanks for the note. Are you referring to an admin creating a user in the AWS Cognito console?

**Comment by dbroadhurst** [comment]
Fixed, admin can add a new user and the user will be challenged for a new password when they sign in
