### ISSUE TITLE
Show some user details in the landing page

### ISSUE THREAD

**Issue by ddewaele** [dbroadhurst/aws-cognito-react#2]
After a successful login, it would be nice to display some user info on the landing page

- the encoded JWT token (AccessToken in AuthenticationResult), so it can be used to perform backend authentication)
- Information from the decoded JWT token (username, custom attributes, expiration, groups,....)

**Comment by jpabbuehl** [comment]
Any updates ? Would be very nice features

**Comment by dbroadhurst** [comment]
I just published a new release with some new features. I agree adding some of the tokens would be useful. I'll create a protected route to display useful info

btw - I somehow missed these issues but I do intend a big push in 2018 to make a useful tool

**Comment by dbroadhurst** [comment]
New release shows tokens after signing
